Name:           ros-indigo-rtshell
Version:        3.0.1
Release:        2%{?dist}
Summary:        ROS rtshell package

Group:          Development/Libraries
License:        EPL
URL:            http://ros.org/wiki/openrtm_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rtctree
Requires:       ros-indigo-rtsprofile
BuildRequires:  omniORB-devel
BuildRequires:  python-omniORB
BuildRequires:  python-setuptools
BuildRequires:  ros-indigo-catkin

%description
Shell commands for managing RT-Middleware running on OpenRTM-aist.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Feb 11 2015 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 3.0.1-2
- Autogenerated by Bloom

* Fri Dec 19 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 3.0.1-1
- Autogenerated by Bloom

* Fri Dec 19 2014 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 3.0.1-0
- Autogenerated by Bloom

